(ns ucl.api
  "ucl on Squint -- the LeetCode host. The emit map is ucl.js-emit's, in the
   Squint flavor; the model is in ucl.contract.

   Squint loads this file for macros only because the word d-e-f-m-a-c-r-o
   appears in it (H6): every macro here is generated by contract/defapi.
   defmacro -- this marker is load-bearing; run-tests.sh fails without it."
  (:refer-clojure :exclude [make-array min max defstruct defmethod])
  (:require [ucl.contract :as contract]
            [ucl.js-emit :as js-emit]))

(js-emit/defhelpers false)

(contract/defruntime
  {:positive-infinity js/Infinity
   :negative-infinity (- js/Infinity)})

(def flavor
  {:array-literal (fn [items] (vec items))   ; a vector literal IS a JS array here
   :local-tag     (fn [_ _] nil)
   :tags?         false
   :key-literal   identity                   ; keywords are strings already
   :key-runtime   identity
   :vector-reads? false
   :check-arity?  false
   :safety        (fn [env] (get env :ucl/safety))})   ; squint.edn key (H5)

(defn emit [env] (js-emit/emit-map flavor env))

(contract/defapi (emit &env))
