;; GENERATED by ucl/ansi/translate.clj from the ANSI Common Lisp test suite
;; (ansi-test.common-lisp.dev, commit ca06bd919661af162c67407c9d994e881870bdb3; Copyright 2004 Paul F. Dietz,
;; MIT licence). Do not edit: change the translator and run it again.
;; Each case keeps its ansi-test name; ucl/ansi/REPORT.md lists what was skipped.
(ns ucl.ansi-loop-test
  (:require [ucl.test :refer [deftest is testing]]
            [ucl.api :as ucl]))

(defn contents
  "A host vector's elements as a Clojure vector; ucl/conformance.clj reads it as identity."
  [v]
  (loop [i 0 acc []]
    (if (< i (ucl/length v)) (recur (inc i) (conj acc (ucl/elt v i))) acc)))

(deftest ansi-loop-1-conformance-test
  (testing "sloop.1" (is (= :a (ucl/loop (ucl/return :a)))))
  (testing "sloop.2" (is (= [] (ucl/loop (ucl/return (vector))))))
  (testing "sloop.3" (is (= [:a :b :c :d] (ucl/loop (ucl/return (vector :a :b :c :d))))))
  (testing "sloop.4" (is (= :b (ucl/block nil (ucl/loop (ucl/return :a)) :b)))))

(deftest ansi-loop8-1-conformance-test
  (testing "loop.8.1" (is (= 1 (ucl/loop with x = 1 do (ucl/return x)))))
  (testing "loop.8.6" (is (= 2 (ucl/loop with a fixnum = 2 return a))))
  (testing "loop.8.11" (is (= 0 (ucl/loop with a of-type fixnum return a))))
  (testing "loop.8.13" (is (= nil (ucl/loop with a of-type t return a))))
  (testing "loop.8.17" (is (= nil (ucl/loop with nil = nil return nil)))))

(deftest ansi-loop10-1-conformance-test
  (testing "loop.10.1" (is (= 4 (ucl/loop for x from 1 to 10 count (< x 5)))))
  (testing "loop.10.2" (is (= 6 (ucl/loop for x from 1 to 10 counting (< x 7)))))
  (testing "loop.10.3" (is (= 4 (ucl/loop for x from 1 to 10 count (< x 5) fixnum))))
  (testing "loop.10.4" (is (= 4 (ucl/loop for x from 1 to 10 count (< x 5) of-type integer))))
  (testing "loop.10.5" (is (= [nil 4] (ucl/let ((z nil)) (vector (ucl/loop for x from 1 to 10 count (< x 5) into foo finally (ucl/setf z foo)) z)))))
  (testing "loop.10.6" (is (= [nil 4] (ucl/let ((z nil)) (vector (ucl/loop for x from 1 to 10 count (< x 5) into foo fixnum finally (ucl/setf z foo)) z)))))
  (testing "loop.10.7" (is (= [nil 4] (ucl/let ((z nil)) (vector (ucl/loop for x from 1 to 10 count (< x 5) into foo of-type (integer 0 100) finally (ucl/setf z foo)) z)))))
  (testing "loop.10.59" (is (= 1 (ucl/loop for i from 1 to 10 minimize i maximize (- i)))))
  (testing "loop.10.60" (is (= -1 (ucl/loop for i from 1 to 10 maximize (- i) minimize i))))
  (testing "loop.10.61" (is (= -1 (ucl/loop for i from 5 downto 1 maximize i minimize (- i)))))
  (testing "loop.10.70" (is (= 10 (ucl/loop for i from 1 to 4 sum i))))
  (testing "loop.10.71" (is (= 10 (ucl/loop for i from 1 to 4 summing i))))
  (testing "loop.10.74" (is (= 10 (ucl/loop for i from 1 to 4 sum i fixnum))))
  (testing "loop.10.75" (is (= 10 (ucl/loop for i from 1 to 4 sum i of-type integer))))
  (testing "loop.10.76" (is (= 10 (ucl/loop for i from 1 to 4 sum i of-type rational))))
  (testing "loop.10.78" (is (= 10 (ucl/loop for i from 1 to 4 sum i of-type number))))
  (testing "loop.10.79" (is (= 10 (ucl/loop for i from 1 to 4 sum i into foo finally (ucl/return foo)))))
  (testing "loop.10.80" (is (= 10 (ucl/loop for i from 1 to 4 sum i into foo fixnum finally (ucl/return foo)))))
  (testing "loop.10.81" (is (= [nil 10] (ucl/let ((z nil)) (vector (ucl/loop for i from 1 to 4 sum i into foo of-type (integer 0 10) finally (ucl/setf z foo)) z)))))
  (testing "loop.10.82" (is (= 14 (ucl/loop for i from 1 to 4 sum i fixnum count true))))
  (testing "loop.10.83" (is (= 14 (ucl/loop for i from 1 to 4 sum i fixnum count true fixnum))))
  (testing "loop.10.84" (is (= [10 100] (ucl/let ((foo 100)) (vector (ucl/loop for i from 1 to 4 sum i into foo of-type integer finally (ucl/return foo)) foo)))))
  (testing "loop.10.90" (is (= [10 14] (ucl/loop for i from 1 to 4 sum i into foo sum (inc i) into bar finally (ucl/return (vector foo bar)))))))

(deftest ansi-loop11-1-conformance-test
  (testing "loop.11.1" (is (= [nil 10] (ucl/let ((z 0)) (vector (ucl/loop repeat 10 do (ucl/incf z)) z)))))
  (testing "loop.11.3" (is (= 0 (ucl/let ((z 0)) (ucl/loop repeat 0 do (ucl/incf z)) z))))
  (testing "loop.11.4" (is (= 0 (ucl/let ((z 0)) (ucl/loop repeat -1 do (ucl/incf z)) z))))
  (testing "loop.11.6" (is (= 0 (ucl/let ((z 0)) (ucl/loop repeat -1000000000000 do (ucl/incf z)) z))))
  (testing "loop.11.18" (is (= 6 (ucl/loop for i from 1 to 10 while (< i 6) finally (ucl/return i)))))
  (testing "loop.11.28" (is (= 6 (ucl/loop for i from 1 to 10 until (>= i 6) finally (ucl/return i))))))

(deftest ansi-loop13-1-conformance-test
  (testing "loop.13.1" (is (= 10 (ucl/loop do (ucl/return 10)))))
  (testing "loop.13.2" (is (= 10 (ucl/loop doing (ucl/return 10)))))
  (testing "loop.13.3" (is (= 56 (ucl/loop for i from 0 below 100 by 7 when (> i 50) return i))))
  (testing "loop.13.4" (is (= 10 (ucl/let ((x 0)) (ucl/loop do (ucl/incf x) (when (== x 10) (ucl/return x)))))))
  (testing "loop.13.5" (is (= :a (ucl/loop return :a))))
  (testing "loop.13.6" (is (= [] (ucl/loop return (vector)))))
  (testing "loop.13.7" (is (= [1 2] (ucl/loop return (vector 1 2)))))
  (testing "loop.13.9" (is (= :a (ucl/loop named foo return :a))))
  (testing "loop.13.10" (is (= :good (ucl/block nil (ucl/return (ucl/loop named foo return :good)) :bad))))
  (testing "loop.13.11" (is (= :good (ucl/block nil (ucl/loop named foo do (ucl/return :good)) :bad))))
  (testing "loop.13.46" (is (= :good (ucl/loop named foo initially (ucl/return-from foo :good) return :bad))))
  (testing "loop.13.86" (is (= :good (ucl/block nil (ucl/loop named foo initially (ucl/return :good) return :bad) :bad)))))

(deftest ansi-loop15-1-conformance-test
  (testing "loop.15.32" (is (= [1 2] (ucl/loop :with x = 1 :and y = 2 :return (vector x y)))))
  (testing "loop.15.33" (is (= 1 (ucl/loop :named foo :doing (ucl/return-from foo 1)))))
  (testing "loop.15.34" (is (= 2 (ucl/let ((x 0)) (ucl/loop :initially (ucl/setf x 2) :until true :finally (ucl/return x))))))
  (testing "loop.15.49" (is (= [30 25] (ucl/loop :for x :upfrom 1 :to 10 :if (even? x) :sum x :into foo :else :sum x :into bar :end :finally (ucl/return (vector foo bar))))))
  (testing "loop.15.50" (is (= [30 25] (ucl/loop :for x :downfrom 10 :above 0 :when (even? x) :sum x :into foo :else :sum x :into bar :end :finally (ucl/return (vector foo bar)))))))

(deftest ansi-loop16-1-conformance-test
  (testing "loop.16.32" (is (= [1 2] (ucl/loop with x = 1 and y = 2 return (vector x y)))))
  (testing "loop.16.33" (is (= 1 (ucl/loop named foo doing (ucl/return-from foo 1)))))
  (testing "loop.16.34" (is (= 2 (ucl/let ((x 0)) (ucl/loop initially (ucl/setf x 2) until true finally (ucl/return x))))))
  (testing "loop.16.49" (is (= [30 25] (ucl/loop for x upfrom 1 to 10 if (even? x) sum x into foo else sum x into bar end finally (ucl/return (vector foo bar))))))
  (testing "loop.16.50" (is (= [30 25] (ucl/loop for x downfrom 10 above 0 when (even? x) sum x into foo else sum x into bar end finally (ucl/return (vector foo bar)))))))

(deftest ansi-loop17-1-conformance-test
  (testing "loop.17.1" (is (= 336 (ucl/loop with x = 0 initially (ucl/incf x 1) (ucl/incf x (+ x x)) initially (ucl/incf x (+ x x x)) until true finally (ucl/incf x 100) (ucl/incf x (+ x x)) finally (ucl/return x)))))
  (testing "loop.17.2" (is (= 336 (ucl/loop with x = 0 until true initially (ucl/incf x 1) (ucl/incf x (+ x x)) finally (ucl/incf x 100) (ucl/incf x (+ x x)) initially (ucl/incf x (+ x x x)) finally (ucl/return x)))))
  (testing "loop.17.3" (is (= [3 1] (ucl/let ((x 0)) (ucl/loop with y = (ucl/incf x 1) initially (ucl/incf x 2) until true finally (ucl/return (vector x y)))))))
  (testing "loop.17.4" (is (= :a (ucl/loop doing (ucl/return :a) finally (ucl/return :b)))))
  (testing "loop.17.5" (is (= :a (ucl/loop return :a finally (ucl/return :b))))))
