(ns ucl.seq
  "Common Lisp's sequence functions over vectors (README §4.2, D44–D52).

   Each is one shared expansion over ucl's own forms, registered with the
   contract (I23): return-position assignment (D35) runs one as a statement
   and the walker expands one before walking it. The macros themselves are
   generated by contract/defapi from `contract/vocabulary-names`.

   A function argument -- a predicate, `reduce`'s function, `:key`, `:test` --
   is applied in one of four ways (D46–D48):
     a literal fn       its body is written into the loop, its parameters
                        bound to the elements
     a symbol           called in function position
     a curried form     a sequence function short of its sequence: the
                        element is spliced in as that sequence
     anything else      evaluated once, before the loop, and called
   Applying one takes a continuation, the code that uses its value. A literal
   fn's body ends in `let` or `do` often; written into an `if` test or a
   `recur` argument as it is, that would be an expression-position `let`, an
   IIFE on Squint (H22). So the continuation is pushed into the body's tail,
   unless a name the body binds occurs in the continuation's code.

   An expander never reads the lexical environment (I23): what needs a local's
   type it emits as a ucl form, `ucl.api/elt` and `ucl.api/length`, which
   expand later where the environment is right.

   Squint loads this file into its macro interpreter only if the word
   d-e-f-m-a-c-r-o appears in it (H6): defmacro -- the marker is load-bearing."
  (:require [ucl.contract :as contract]))

;; ===========================================================================
;; Small helpers
;; ===========================================================================

(defn ^:macro-support api [sym] (symbol "ucl.api" (name sym)))

(defn ^:macro-support ucl-call?
  "Is `form` a call through a namespace other than Clojure's own? Clients
   always call ucl through its alias (D25); a bare `count` or `reduce` is
   Clojure's, and the walker must leave it alone."
  [form]
  (let [h (first form)]
    (and (symbol? h)
         (some? (namespace h))
         (not (contains? #{"clojure.core" "cljs.core" "cljd.core"} (namespace h))))))

(defn ^:macro-support keyword-tail?
  "Alternating literal keywords and values."
  [xs]
  (and (even? (count xs)) (every? keyword? (take-nth 2 xs))))

(defn ^:macro-support counter
  "A fresh loop counter, hinted as a fixnum where the host types locals by
   hint (I20)."
  [backend prefix]
  (let [v (gensym prefix)
        h ((contract/op backend :types :local-hint) :fixnum)]
    (if h (vary-meta v assoc :tag h) v)))

(defn ^:macro-support binder
  "Bindings evaluated once, left to right, in the order they are added.
   `(bind st form prefix)` returns [st' ref]: a trivial form is used as is."
  [] [])

(defn ^:macro-support bind [st form prefix]
  (if (contract/trivial? form)
    [st form]
    (let [g (gensym prefix)] [(conj st g form) g])))

;; ===========================================================================
;; The functions: required arguments, keywords, curried forms (D48, D50)
;; ===========================================================================
;; `:seq-pos` -- where the sequence is among the required arguments (second
;; unless given); with two sequences, the one written (D50). `:nopt` --
;; optional positional arguments (`subseq`'s end). `:rest` -- the `every`
;; family takes one or more sequences and has no curried form (D50).

(defn ^:macro-support specs []
  {"count"            {:nreq 2 :keys #{:from-end :start :end :key :test :test-not}}
   "count-if"         {:nreq 2 :keys #{:from-end :start :end :key}}
   "count-if-not"     {:nreq 2 :keys #{:from-end :start :end :key}}
   "find"             {:nreq 2 :keys #{:from-end :start :end :key :test :test-not}}
   "find-if"          {:nreq 2 :keys #{:from-end :start :end :key}}
   "find-if-not"      {:nreq 2 :keys #{:from-end :start :end :key}}
   "position"         {:nreq 2 :keys #{:from-end :start :end :key :test :test-not}}
   "position-if"      {:nreq 2 :keys #{:from-end :start :end :key}}
   "position-if-not"  {:nreq 2 :keys #{:from-end :start :end :key}}
   "reduce"           {:nreq 2 :keys #{:key :from-end :start :end :initial-value}}
   "every"            {:nreq 2 :rest true}
   "some"             {:nreq 2 :rest true}
   "notany"           {:nreq 2 :rest true}
   "notevery"         {:nreq 2 :rest true}
   "fill"             {:nreq 2 :seq-pos 0 :keys #{:start :end}}
   "replace"          {:nreq 2 :seq-pos 0 :keys #{:start1 :end1 :start2 :end2}}
   "copy-seq"         {:nreq 1 :seq-pos 0 :keys #{}}
   "subseq"           {:nreq 2 :nopt 1 :seq-pos 0}
   "reverse"          {:nreq 1 :seq-pos 0 :keys #{}}
   "nreverse"         {:nreq 1 :seq-pos 0 :keys #{}}
   "sort"             {:nreq 2 :seq-pos 0 :keys #{:key}}
   "stable-sort"      {:nreq 2 :seq-pos 0 :keys #{:key}}
   "remove"           {:nreq 2 :keys #{:from-end :start :end :key :test :test-not :count}}
   "remove-if"        {:nreq 2 :keys #{:from-end :start :end :key :count}}
   "remove-if-not"    {:nreq 2 :keys #{:from-end :start :end :key :count}}
   "delete"           {:nreq 2 :keys #{:from-end :start :end :key :test :test-not :count}}
   "delete-if"        {:nreq 2 :keys #{:from-end :start :end :key :count}}
   "delete-if-not"    {:nreq 2 :keys #{:from-end :start :end :key :count}}
   ;; `:new` -- a new item comes before the item or predicate
   "substitute"         {:nreq 3 :seq-pos 2 :new true :keys #{:from-end :start :end :key :test :test-not :count}}
   "substitute-if"      {:nreq 3 :seq-pos 2 :new true :keys #{:from-end :start :end :key :count}}
   "substitute-if-not"  {:nreq 3 :seq-pos 2 :new true :keys #{:from-end :start :end :key :count}}
   "nsubstitute"        {:nreq 3 :seq-pos 2 :new true :keys #{:from-end :start :end :key :test :test-not :count}}
   "nsubstitute-if"     {:nreq 3 :seq-pos 2 :new true :keys #{:from-end :start :end :key :count}}
   "nsubstitute-if-not" {:nreq 3 :seq-pos 2 :new true :keys #{:from-end :start :end :key :count}}})

(defn ^:macro-support call-shape
  "`:full`, `:curried` (every argument but the sequence), or nil."
  [spec args]
  (let [n (:nreq spec)
        o (or (:nopt spec) 0)
        c (count args)]
    (cond (:rest spec)                               (when (>= c n) :full)
          ;; optional positionals and no keywords: only one argument short
          ;; is curried, so (subseq v 2) is a call and (subseq 2) a function
          (pos? o)                                   (cond (<= n c (+ n o)) :full
                                                           (= c (dec n))   :curried
                                                           :else nil)
          (and (>= c n) (keyword-tail? (drop n args))) :full
          (and (>= c (dec n))
               (keyword-tail? (drop (dec n) args)))  :curried
          :else nil)))

(defn ^:macro-support splice-sequence
  "The call `form`, short of its sequence, with `s` put where the sequence goes."
  [spec form s]
  (let [[h & args] form
        p (if (contains? spec :seq-pos) (:seq-pos spec) 1)]
    (list* h (concat (take p args) [s] (drop p args)))))

(defn ^:macro-support usage [fname]
  (case fname
    ("count" "find" "position") (str "(" fname " item sequence &key from-end start end key test test-not)")
    ("remove" "delete")         (str "(" fname " item sequence &key from-end test test-not start end count key)")
    ("remove-if" "remove-if-not" "delete-if" "delete-if-not")
    (str "(" fname " predicate sequence &key from-end start end count key)")
    ("substitute" "nsubstitute") (str "(" fname " newitem olditem sequence &key from-end test test-not start end count key)")
    ("substitute-if" "substitute-if-not" "nsubstitute-if" "nsubstitute-if-not")
    (str "(" fname " newitem predicate sequence &key from-end start end count key)")
    "reduce"                    "(reduce function sequence &key key from-end start end initial-value)"
    ("every" "some" "notany" "notevery") (str "(" fname " predicate sequence &rest sequences)")
    "fill"                      "(fill sequence item &key start end)"
    "replace"                   "(replace sequence-1 sequence-2 &key start1 end1 start2 end2)"
    ("copy-seq" "reverse" "nreverse") (str "(" fname " sequence)")
    "subseq"                    "(subseq sequence start &optional end)"
    ("sort" "stable-sort")      (str "(" fname " sequence predicate &key key)")
    (str "(" fname " predicate sequence &key from-end start end key)")))

(defn ^:macro-support parse-keys
  "The keyword arguments of a call, in written order, after checking them:
   a key the function does not take is allowed only when the leftmost
   `:allow-other-keys` is true (CLHS 3.4.1.4.1). A macro decides that at
   expansion, so with other keys present the value must be a literal."
  [fname spec kvs form]
  (let [pairs   (mapv vec (partition 2 kvs))
        aok     (first (filter #(= :allow-other-keys (first %)) pairs))
        unknown (remove #(or (contains? (:keys spec) (first %)) (= :allow-other-keys (first %))) pairs)]
    (when (seq unknown)
      (let [k (ffirst unknown)
            v (second aok)]
        (cond
          (nil? aok)
          (contract/fail! (str fname " does not take " k ". It takes "
                               (pr-str (vec (sort (:keys spec)))) ", or others with :allow-other-keys true -- "
                               (usage fname))
                          {:form form})
          (not (contract/literal? v))
          (contract/fail! (str fname " is given " k " with :allow-other-keys " (pr-str v)
                               ", which is only known at run time. Write :allow-other-keys true, or leave out " k)
                          {:form form})
          (or (nil? v) (false? v))
          (contract/fail! (str fname " does not take " k " (:allow-other-keys is " (pr-str v) ")")
                          {:form form}))))
    {:order pairs}))

(defn ^:macro-support literal-nil? [f] (nil? f))

;; ===========================================================================
;; Applying a function argument (D46–D48)
;; ===========================================================================

(defn ^:macro-support fn-literal? [f]
  (and (seq? f) (contains? #{"fn" "fn*"} (contract/head-name f))))

(defn ^:macro-support fn-arity
  "[params body] of the literal fn `f`'s arity for `n` arguments, or nil: no
   such arity, a rest parameter, or a named fn whose body calls itself."
  [f n]
  (let [more     (rest f)
        fname    (when (symbol? (first more)) (first more))
        more     (if fname (rest more) more)
        arities  (if (vector? (first more)) [more] more)
        hit      (first (filter (fn [a] (and (seq? a) (vector? (first a))
                                             (= n (count (first a)))
                                             (not (some #{'&} (first a)))))
                                (if (vector? (first more)) [more] arities)))]
    (when (and hit (not (and fname (contract/mentions? (rest hit) #{fname}))))
      [(first hit) (rest hit)])))

(defn ^:macro-support curried-form?
  "A sequence function given every argument but its sequence (D48)."
  [f]
  (and (seq? f) (symbol? (first f)) (ucl-call? f)
       (let [spec (get (specs) (name (first f)))]
         (and spec (= :curried (call-shape spec (rest f)))))))

(defn ^:macro-support designator
  "The function a quoted symbol or `#'f` names: `'f` is Common Lisp's
   designator for the global function f (CLHS 1.4.1.5), and Clojure reads
   `#'f` as `(var f)`."
  [f]
  (when (and (seq? f) (contains? #{'quote 'var} (first f)) (symbol? (second f)) (nil? (nnext f)))
    (second f)))

(defn ^:macro-support fn-spec
  "How to apply the function argument `f`, given the binder; returns [st spec]."
  [st f]
  (cond (fn-literal? f)    [st {:kind :inline :form f}]
        (symbol? f)        [st {:kind :call :f f}]
        (designator f)     [st {:kind :call :f (designator f)}]
        (curried-form? f)  [st {:kind :curried :form f}]
        :else              (let [[st g] (bind st f "f")] [st {:kind :call :f g}])))

(defn ^:macro-support push-into
  "`(k body)`, with `k` pushed into the tail of `body` when that is a `let` or
   `do` and pushing captures nothing; see the namespace doc."
  [body k]
  (let [h (contract/head-name body)]
    (cond
      (and (contains? #{"let" "let*"} h) (vector? (second body)) (seq (nnext body)))
      (let [bound (set (contract/binding-symbols (vec (take-nth 2 (second body)))))]
        (if (contract/mentions? (k (gensym "probe")) bound)
          (k body)
          (concat (butlast body) [(push-into (last body) k)])))

      (and (= "do" h) (seq (rest body)))
      (concat (butlast body) [(push-into (last body) k)])

      :else (k body))))

(defn ^:macro-support apply-fn
  "Apply the function argument `spec` to `args` (forms that are free to repeat:
   symbols), passing the value's form to the continuation `k`."
  [spec args k]
  (case (:kind spec)
    :identity (k (first args))
    :call     (k (cons (:f spec) args))
    :curried  (let [f (:form spec)]
                (k (splice-sequence (get (specs) (name (first f))) f (first args))))
    :inline   (let [[params body] (or (fn-arity (:form spec) (count args))
                                      (contract/fail!
                                       (str "the fn " (pr-str (:form spec)) " takes no "
                                            (count args) " arguments, but is called with "
                                            (count args) " here")
                                       {:form (:form spec)}))
                    body (if (next body) (cons 'do body) (first body))
                    bound (set (contract/binding-symbols params))]
                (if (contract/mentions? (k (gensym "probe")) bound)
                  (k (list 'let (vec (interleave params args)) body))
                  (list 'let (vec (interleave params args)) (push-into body k))))))

(defn ^:macro-support apply-key
  "Apply `:key` (identity when absent) to the element `e`, then `k`."
  [key-spec e k]
  (apply-fn (or key-spec {:kind :identity}) [e] k))

(defn ^:macro-support item-test
  "The continuation-passing test of `item` against a key value: `:test`,
   `:test-not` or `eql` (D52)."
  [backend fname test-spec test-not-spec item form]
  (when (and test-spec test-not-spec)
    (contract/fail! (str fname " takes :test or :test-not, not both (CLHS 17.2.1)")
                    {:form form}))
  (cond test-spec     (fn [kv k] (apply-fn test-spec [item kv] k))
        test-not-spec (fn [kv k] (apply-fn test-not-spec [item kv] (fn [t] (k (list 'not t)))))
        :else         (fn [kv k] (k ((contract/op backend :seqfn :eql) item kv)))))

;; ===========================================================================
;; Index loops
;; ===========================================================================

(defn ^:macro-support bind-keys
  "Evaluate every keyword value once, in written order; the leftmost
   occurrence of a key is the one used (CLHS 3.4.1.4). Keys in `fn-keys` take
   functions; a literal nil `:key` is identity (CLHS 17.2.1). Returns
   [st {key ref-or-spec}]."
  [st order fn-keys]
  (reduce (fn [[st m] [k f]]
            (let [use (fn [st x] [st (if (contains? m k) m (assoc m k x))])]
              (cond (and (= :key k) (literal-nil? f)) (use st nil)
                    (contains? fn-keys k)             (let [[st x] (fn-spec st f)] (use st x))
                    :else                             (let [[st x] (bind st f (name k))] (use st x)))))
          [st {}] order))

(defn ^:macro-support index-loop
  "(loop [i first, state...] (if in-range (body i next) exit)), stepping up
   from `s` below `e`, or down from below `e` to `s` when `from-end`.
   `body` gets the counter and `next`, a fn of the new state values that
   returns the `recur`."
  [backend s e from-end state body exit]
  (let [i      (counter backend "i")
        first* (if from-end (list 'dec e) s)
        test   (if from-end (list '>= i s) (list '< i e))
        step   (if from-end (list 'dec i) (list 'inc i))
        nxt    (fn [& vals] (list* 'recur step vals))]
    (list 'loop (vec (concat [i first*] (mapcat identity state)))
          (list 'if test (body i nxt) exit))))

(defn ^:macro-support bounds
  "[st s e]: the `:start` and `:end` (or `sk`/`ek`) of sequence `v`. An end
   that is not a literal may be nil at run time, meaning the length (CLHS
   17.1.1)."
  ([st v keys] (bounds st v keys :start :end))
  ([st v keys sk ek]
  (let [s (get keys sk 0)
        e (get keys ek)]
    [st s (cond (nil? e)    (list (api 'length) v)
                (number? e) e
                :else       (list 'if (list 'nil? e) (list (api 'length) v) e))])))

(defn ^:macro-support check-bounds
  "At safety >= 1, a binding that signals unless 0 <= s <= e <= length
   (CLHS 17.1.1); nothing at safety 0."
  [backend st v s e]
  (if (pos? (contract/safety backend))
    (conj st (gensym "_")
          (list 'if (list 'and (list '<= 0 s) (list '<= s e) (list '<= e (list (api 'length) v)))
                nil
                ((contract/op backend :seqfn :fail)
                 "bounding indices must satisfy 0 <= start <= end <= length (CLHS 17.1.1)")))
    st))

(defn ^:macro-support finish [st body] (contract/wrap-let st body))

;; ===========================================================================
;; count, find, position (and their -if, -if-not)
;; ===========================================================================

(defn ^:macro-support predicate-name? [^String fname]
  (or (.endsWith fname "-if") (.endsWith fname "-if-not")))

(defn ^:macro-support parse-search
  "Shared front of the item and predicate functions: binds arguments in
   CLHS order -- a new item, the item or predicate, the sequence, then each
   keyword value as written -- and returns what an expansion needs."
  [backend fname form]
  (let [spec        (get (specs) fname)
        [newitem a0 sq & kvs] (if (:new spec) (rest form) (cons nil (rest form)))
        if?         (predicate-name? fname)
        st          (binder)
        [st new]    (if (:new spec) (bind st newitem "new") [st nil])
        [st item pred] (if if?
                         (let [[st p] (fn-spec st a0)] [st nil p])
                         (let [[st x] (bind st a0 "item")] [st x nil]))
        [st v]      (bind st sq "v")
        {:keys [order]} (parse-keys fname spec kvs form)
        [st kforms] (bind-keys st order #{:key :test :test-not})
        [st s e]    (bounds st v kforms)
        [st s]      (bind st s "s")
        [st e]      (bind st e "e")
        st          (check-bounds backend st v s e)
        negate?     (and if? (.endsWith ^String fname "-not"))
        test        (if if?
                      (fn [kv k] (apply-fn pred [kv] (if negate? (fn [t] (k (list 'not t))) k)))
                      (item-test backend fname (:test kforms) (:test-not kforms) item form))]
    {:st st :v v :s s :e e :from-end (get kforms :from-end) :key (:key kforms) :test test
     :new new :keys kforms}))

(defn ^:macro-support search-loop
  "A search in one direction: `found` builds the return value from the
   element and the index."
  [backend {:keys [v s e key test]} from-end found exit-value]
  (index-loop backend s e from-end []
              (fn [i nxt]
                (let [el (gensym "el")]
                  (list 'let [el (list (api 'elt) v i)]
                        (apply-key key el
                                   (fn [kv] (test kv (fn [t] (list 'if t (found el i) (nxt)))))))))
              exit-value))

(defn ^:macro-support both-directions
  "A `:from-end` known at compile time picks one loop; otherwise both are
   emitted and the flag chooses at run time."
  [from-end build]
  (cond (or (nil? from-end) (false? from-end)) (build false)
        (true? from-end)                       (build true)
        :else (list 'if from-end (build true) (build false))))

(defn ^:macro-support expand-count [backend form]
  ;; :from-end changes only the order the test sees the elements in
  (let [p (parse-search backend (name (first form)) form)
        c (counter backend "c")]
    (finish (:st p)
            (both-directions
             (:from-end p)
             (fn [fe]
               (index-loop backend (:s p) (:e p) fe [[c 0]]
                           (fn [i nxt]
                             (let [el (gensym "el")]
                               (list 'let [el (list (api 'elt) (:v p) i)]
                                     (apply-key (:key p) el
                                                (fn [kv] ((:test p) kv
                                                          (fn [t] (nxt (list 'if t (list 'inc c) c)))))))))
                           c))))))

(defn ^:macro-support expand-find [backend form]
  (let [p (parse-search backend (name (first form)) form)]
    (finish (:st p) (both-directions (:from-end p)
                                     (fn [fe] (search-loop backend p fe (fn [el _] el) nil))))))

(defn ^:macro-support expand-position [backend form]
  (let [p (parse-search backend (name (first form)) form)]
    (finish (:st p) (both-directions (:from-end p)
                                     (fn [fe] (search-loop backend p fe (fn [_ i] i) nil))))))

;; ===========================================================================
;; every, some, notany, notevery
;; ===========================================================================

(defn ^:macro-support expand-quantifier [backend form]
  (let [fname   (name (first form))
        [_ f & seqs] form
        st      (binder)
        [st pred] (fn-spec st f)
        [st vs] (reduce (fn [[st acc] sq] (let [[st v] (bind st sq "v")] [st (conj acc v)]))
                        [st []] seqs)
        n       (if (next vs)
                  (cons (api 'min) (map #(list (api 'length) %) vs))
                  (list (api 'length) (first vs)))
        [st n]  (bind st n "n")
        r       (gensym "r")
        on-true (fn [t nxt] (case fname
                              "every"    (list 'if t (nxt) nil)
                              "some"     (list 'let [r t] (list 'if r r (nxt)))
                              "notany"   (list 'if t nil (nxt))
                              "notevery" (list 'if t (nxt) true)))
        exit    (case fname "every" true "some" nil "notany" true "notevery" nil)]
    (finish st
            (index-loop backend 0 n false []
                        (fn [i nxt]
                          (let [els (mapv (fn [_] (gensym "el")) vs)]
                            (list 'let (vec (mapcat (fn [el v] [el (list (api 'elt) v i)]) els vs))
                                  (apply-fn pred els (fn [t] (on-true t nxt))))))
                        exit))))

;; ===========================================================================
;; reduce
;; ===========================================================================

(defn ^:macro-support operator-name
  "The name of an arithmetic or comparison operator: Clojure's, unqualified or
   from clojure.core, or ucl's min and max."
  [f]
  (when (symbol? f)
    (let [ns (namespace f)]
      (when (or (nil? ns) (contains? #{"clojure.core" "cljs.core" "cljd.core"} ns)
                (contains? #{"min" "max"} (name f)))
        (name f)))))

(defn ^:macro-support operator-zero
  "The value of a call with no arguments, for the operators that have one."
  [f]
  (case (operator-name f) "+" 0 "*" 1 nil))

(defn ^:macro-support operator-needs-args? [f]
  (contains? #{"-" "/" "min" "max" "<" ">" "<=" ">=" "==" "=" "not=" "quot" "rem" "mod"
               "bit-and" "bit-or" "bit-xor"}
             (operator-name f)))

(defn ^:macro-support zero-call
  "`(function)`, for an empty range without :initial-value (CLHS reduce)."
  [backend spec form]
  (cond (and (= :call (:kind spec)) (operator-zero (:f spec)))
        (operator-zero (:f spec))

        ;; an operator that needs arguments: hosts inline operators, and a
        ;; call with none can fail to compile (Squint emits `()`)
        (and (= :call (:kind spec)) (operator-needs-args? (:f spec)))
        (if (pos? (contract/safety backend))
          ((contract/op backend :seqfn :fail)
           (str "reduce of an empty sequence without :initial-value calls " (:f spec)
                " with no arguments"))
          nil)

        (= :call (:kind spec))
        (list (:f spec))
        (and (= :inline (:kind spec)) (fn-arity (:form spec) 0))
        (apply-fn spec [] identity)
        (pos? (contract/safety backend))
        ((contract/op backend :seqfn :fail)
         (str "reduce of an empty sequence without :initial-value calls its function with no arguments, which "
              (pr-str (or (:form spec) (:f spec))) " does not take"))
        :else nil))

(defn ^:macro-support integer-preserving?
  "Does the function spec `fs` return an integer when given integers?"
  [fs]
  (and (= :call (:kind fs))
       (contains? #{"min" "max" "+" "-" "*" "bit-and" "bit-or" "bit-xor"} (operator-name (:f fs)))))

(defn ^:macro-support integer-elements?
  "Are the elements of the sequence `v` declared integers (I48)? Only a
   symbol can say, through the backend's environment -- and not one that an
   early expansion's enclosing form cannot see rebound (`:rebound`)."
  [backend v]
  (let [r (:rebound backend)]
    (and (symbol? v)
         (not= :all r)
         (not (contains? r v))
         (contains? #{:fixnum :sb53} ((contract/op backend :types :vector-element) v)))))

(defn ^:macro-support accumulator
  "reduce's accumulator, hinted as an integer where the host types locals by
   hint and the value is surely one (I48): a typed loop local on Dart AOT is
   2-4x a dynamic one."
  [backend v fs kf]
  (let [acc (gensym "acc")
        h   ((contract/op backend :types :local-hint) :fixnum)
        init (get kf :initial-value)]
    (if (and h
             (nil? (:key kf))
             (or (not (contains? kf :initial-value)) (integer? init))
             (integer-preserving? fs)
             (integer-elements? backend v))
      (vary-meta acc assoc :tag h)
      acc)))

(defn ^:macro-support expand-reduce [backend form]
  (let [[_ f sq & kvs] form
        spec      (get (specs) "reduce")
        st        (binder)
        [st fs]   (fn-spec st f)
        [st v]    (bind st sq "v")
        {:keys [order]} (parse-keys "reduce" spec kvs form)
        [st kf]   (bind-keys st order #{:key})
        [st s e]  (bounds st v kf)
        [st s]    (bind st s "s")
        [st e]    (bind st e "e")
        st        (check-bounds backend st v s e)
        init?     (contains? kf :initial-value)
        acc       (accumulator backend v fs kf)
        step      (fn [fe]
                    (fn [i nxt]
                      (let [el (gensym "el")]
                        (list 'let [el (list (api 'elt) v i)]
                              (apply-key (:key kf) el
                                         (fn [kv] (apply-fn fs (if fe [kv acc] [acc kv])
                                                            (fn [r] (nxt r)))))))))
        build     (fn [fe]
                    (if init?
                      (index-loop backend s e fe [[acc (:initial-value kf)]] (step fe) acc)
                      (let [el    (gensym "el")
                            first (if fe (list 'dec e) s)
                            ;; the loop runs over what is left after the first element
                            [s' e'] (if fe [s (list 'dec e)] [(list 'inc s) e])]
                        (list 'if (list '< s e)
                              (list 'let [el (list (api 'elt) v first)]
                                    (apply-key (:key kf) el
                                               (fn [kv] (index-loop backend s' e' fe [[acc kv]] (step fe) acc))))
                              (zero-call backend fs form)))))]
    (finish st (both-directions (:from-end kf) build))))

;; ===========================================================================
;; fill, replace, copy-seq, subseq, reverse, nreverse (I40, I47)
;; ===========================================================================
;; At safety >= 1 each stores through ucl's checked `setf` of `elt`, which
;; signals a store outside a vector's element type. At safety 0 a host's
;; native bulk operation replaces the loop where I40 measured it faster: the
;; backend's `:seqfn` operations return a form, or nil for the loop.

(defn ^:macro-support store [v i x] (list (api 'setf) (list (api 'elt) v i) x))

(defn ^:macro-support counted-statement
  "A loop of a fresh counter over [s, e), upward or downward, running
   `(body i)` for its effect."
  [backend s e from-end body]
  (index-loop backend s e from-end [] (fn [i nxt] (list 'do (body i) (nxt))) nil))

(defn ^:macro-support native [backend op & args]
  (when (zero? (contract/safety backend))
    (apply (contract/op backend :seqfn op) args)))

(defn ^:macro-support expand-fill [backend form]
  (let [[_ sq item & kvs] form
        st       (binder)
        [st v]   (bind st sq "v")
        [st x]   (bind st item "item")
        {:keys [order]} (parse-keys "fill" (get (specs) "fill") kvs form)
        [st kf]  (bind-keys st order #{})
        [st s e] (bounds st v kf)
        [st s]   (bind st s "s")
        [st e]   (bind st e "e")
        st       (check-bounds backend st v s e)]
    (finish st (list 'do
                     (or (native backend :fill v x s e)
                         (counted-statement backend s e false (fn [i] (store v i x))))
                     v))))

(defn ^:macro-support copy-range
  "A statement copying `n` elements of `src` from `s2` into `dst` from `s1`.
   `from-end` true or false gives the direction; `:run-time` copies from the
   end when the vectors are one and the ranges overlap upward, as if through
   a copy (CLHS replace)."
  [backend dst src s1 s2 n from-end]
  (or (native backend :replace dst src s1 s2 n)
      (let [copy (fn [fe]
                   (counted-statement backend 0 n fe
                                      (fn [i] (store dst (list '+ s1 i) (list (api 'elt) src (list '+ s2 i))))))]
        (if (= :run-time from-end)
          (list 'if (list 'and (list 'identical? dst src) (list '> s1 s2)) (copy true) (copy false))
          (copy from-end)))))

(defn ^:macro-support expand-replace [backend form]
  (let [[_ sq1 sq2 & kvs] form
        st         (binder)
        [st v1]    (bind st sq1 "v")
        [st v2]    (bind st sq2 "v")
        {:keys [order]} (parse-keys "replace" (get (specs) "replace") kvs form)
        [st kf]    (bind-keys st order #{})
        [st s1 e1] (bounds st v1 kf :start1 :end1)
        [st s2 e2] (bounds st v2 kf :start2 :end2)
        [st s1]    (bind st s1 "s")
        [st e1]    (bind st e1 "e")
        [st s2]    (bind st s2 "s")
        [st e2]    (bind st e2 "e")
        st         (check-bounds backend st v1 s1 e1)
        st         (check-bounds backend st v2 s2 e2)
        [st n]     (bind st (list (api 'min) (list '- e1 s1) (list '- e2 s2)) "n")]
    (finish st (list 'do (copy-range backend v1 v2 s1 s2 n :run-time) v1))))

(defn ^:macro-support subseq-form
  "A fresh vector of `v`'s elements in [s, e), of `v`'s kind: the host's
   slice (I40)."
  [backend v s e]
  ((contract/op backend :seqfn :subseq) v s e))

(defn ^:macro-support expand-subseq [backend form]
  (let [[_ sq start end] form
        st       (binder)
        [st v]   (bind st sq "v")
        [st s0]  (bind st start "start")
        [st e0]  (if (nil? end) [st nil] (bind st end "end"))
        [st s e] (bounds st v (cond-> {:start s0} (some? e0) (assoc :end e0)))
        ;; one call, used once at safety 0: a `let` here would be an IIFE in
        ;; expression position on Squint (H22); the check uses e twice
        [st e]   (if (pos? (contract/safety backend)) (bind st e "e") [st e])
        st       (check-bounds backend st v s e)]
    (finish st (subseq-form backend v s e))))

(defn ^:macro-support expand-copy-seq [backend form]
  (let [st     (binder)
        [st v] (bind st (second form) "v")]
    (finish st (subseq-form backend v 0 (list (api 'length) v)))))

(defn ^:macro-support reverse-in-place
  "Swap the halves of `v`, of length `n`; then `v`."
  [backend v n]
  (let [a (gensym "a") j (gensym "j")]
    (list 'do
          (counted-statement backend 0 (list 'bit-shift-right n 1) false
                             (fn [i] (list 'let [j (list '- n 1 i) a (list (api 'elt) v i)]
                                           (store v i (list (api 'elt) v j))
                                           (store v j a))))
          v)))

(defn ^:macro-support expand-nreverse [backend form]
  (let [st     (binder)
        [st v] (bind st (second form) "v")
        [st n] (bind st (list (api 'length) v) "n")]
    (finish st (reverse-in-place backend v n))))

(defn ^:macro-support expand-reverse [backend form]
  (let [st     (binder)
        [st v] (bind st (second form) "v")
        [st n] (bind st (list (api 'length) v) "n")
        r      (gensym "r")]
    (finish (conj st r (subseq-form backend v 0 n)) (reverse-in-place backend r n))))

;; ===========================================================================
;; sort, stable-sort (I40, I47)
;; ===========================================================================
;; One bottom-up merge sort for both: stable, so it is a correct `sort` too,
;; and on Dart the fastest choice (§9.13). Its scratch vector is a copy of
;; the sequence, so it has the sequence's kind without a type at expansion
;; (I23). V8's typed sort replaces it for `<` without :key (I40), guarded at
;; run time: a fixnum-vector may be a plain Array, which sorts as strings (H70).

(defn ^:macro-support less-than?
  "Is the predicate `f` Common Lisp's or Clojure's `<`?"
  [f]
  (let [f (or (designator f) f)]
    (and (symbol? f) (= "<" (name f))
         (contains? #{nil "clojure.core" "cljs.core" "cljd.core"} (namespace f)))))

(defn ^:macro-support merge-sort
  "Sort `v` (length `n`) in place, through the scratch vector `tmp`; `less`
   is (fn [a b k]) passing the form of `(pred a b)` to `k`."
  [backend v n tmp less]
  (let [w (counter backend "w") lo (counter backend "lo") c (counter backend "c")
        i (counter backend "i") j (counter backend "j") k (counter backend "k")
        mid (gensym "mid") hi (gensym "hi") a (gensym "a") b (gensym "b")
        el  (fn [x] (list (api 'elt) v x))
        take-j (list 'do (store tmp k (el j)) (list 'recur i (list 'inc j) (list 'inc k)))
        take-i (list 'do (store tmp k (el i)) (list 'recur (list 'inc i) j (list 'inc k)))]
    (list 'loop [w 1]
          (list 'when (list '< w n)
                (list 'loop [lo 0]
                      (list 'when (list '< lo n)
                            (list 'let [mid (list (api 'min) (list '+ lo w) n)
                                        hi  (list (api 'min) (list '+ lo (list '* 2 w)) n)]
                                  (list 'loop [i lo j mid k lo]
                                        (list 'when (list '< k hi)
                                              (list 'if (list '>= i mid) take-j
                                                    (list 'if (list '>= j hi) take-i
                                                          ;; stable: the left element unless the right is less
                                                          (list 'let [a (el j) b (el i)]
                                                                (less a b (fn [t] (list 'if t take-j take-i))))))))
                                  (list 'recur (list '+ lo (list '* 2 w))))))
                (list 'loop [c 0]
                      (list 'when (list '< c n)
                            (store v c (list (api 'elt) tmp c))
                            (list 'recur (list 'inc c))))
                (list 'recur (list '* 2 w))))))

(defn ^:macro-support expand-sort [backend form]
  (let [fname     (name (first form))
        [_ sq pred & kvs] form
        st        (binder)
        [st v]    (bind st sq "v")
        [st ps]   (fn-spec st pred)
        {:keys [order]} (parse-keys fname (get (specs) fname) kvs form)
        [st kf]   (bind-keys st order #{:key})
        [st n]    (bind st (list (api 'length) v) "n")
        tmp       (gensym "tmp")
        key       (:key kf)
        less      (fn [a b k] (apply-key key a (fn [ka] (apply-key key b (fn [kb] (apply-fn ps [ka kb] k))))))
        sorted    (list 'let [tmp (subseq-form backend v 0 n)]
                        (merge-sort backend v n tmp less)
                        v)]
    (finish st (if (and (less-than? pred) (nil? key))
                 ((contract/op backend :seqfn :sort-native) v sorted)
                 sorted))))

;; ===========================================================================
;; remove, delete, substitute, nsubstitute (and their -if, -if-not)
;; ===========================================================================
;; `remove` compacts the kept elements into a copy of the sequence, so the
;; result has the sequence's kind without a type at expansion (I23), then
;; trims it with a second copy -- only when something was removed. `delete`
;; compacts the sequence itself: a vector cannot shrink, so a shorter result
;; is a fresh one (CLHS delete: the result, not the argument, is what counts).
;; `:from-end` changes the result only with `:count` (CLHS remove), but the
;; order the test sees the elements in always, as in SBCL: the suite's tests
;; count the calls (I49).

(defn ^:macro-support count-limit
  "[st limit]: how many elements `:count` lets change, or nil for all. A count
   that is nil at run time is all; a negative one, none (CLHS remove)."
  [st kf e]
  (let [c (get kf :count)]
    (cond (nil? c)    [st nil]
          (number? c) [st c]
          ;; e bounds the number changed: at most e - s elements are
          :else       (bind st (list 'if (list 'nil? c) e c) "limit"))))

(defn ^:macro-support expand-remove [backend form]
  (let [fname     (name (first form))
        in-place? (.startsWith ^String fname "delete")
        p         (parse-search backend fname form)
        {:keys [v s e key test]} p
        ;; without :end, e is the length and there is no tail to move;
        ;; with :start 0, no head
        no-tail?  (nil? (get (:keys p) :end))
        no-head?  (= 0 s)
        [st n]    (if no-tail? [(:st p) e] (bind (:st p) (list (api 'length) v) "n"))
        [st limit] (count-limit st (:keys p) e)
        dst       (if in-place? v (gensym "dst"))
        st        (if in-place? st (conj st dst (subseq-form backend v 0 n)))
        w         (counter backend "w")
        r         (counter backend "r")
        tail      (list '- n e)
        build
        (fn [fe]
          (index-loop
           backend s e fe (cond-> [[w (if fe e s)]] limit (conj [r 0]))
           (fn [i nxt]
             (let [el     (gensym "el")
                   ;; from the end, kept elements fill [w, e) downward
                   at     (if fe (list 'dec w) w)
                   keep   (list 'do (store dst at el)
                                (apply nxt (cond-> [(if fe (list 'dec w) (list 'inc w))] limit (conj r))))
                   drop   (apply nxt (cond-> [w] limit (conj (list 'inc r))))
                   tested (apply-key key el (fn [kv] (test kv (fn [t] (list 'if t drop keep)))))]
               (list 'let [el (list (api 'elt) v i)]
                     (if limit (list 'if (list '< r limit) tested keep) tested))))
           (if fe
             ;; [0, s) moves up to end at w; the result starts there
             (let [from (if no-head? w (list '- w s))]
               (list 'if (list '== w s) dst
                     (if no-head?
                       (subseq-form backend dst from n)
                       (list 'do (copy-range backend dst v from 0 s true)
                             (subseq-form backend dst from n)))))
             ;; [e, n) moves down to start at w
             (list 'if (list '== w e) dst
                   (if no-tail?
                     (subseq-form backend dst 0 w)
                     (list 'do (copy-range backend dst v w e tail false)
                           (subseq-form backend dst 0 (list '+ w tail))))))))]
    (finish st (both-directions (:from-end p) build))))

(defn ^:macro-support expand-substitute [backend form]
  (let [fname     (name (first form))
        in-place? (.startsWith ^String fname "nsubstitute")
        p         (parse-search backend fname form)
        {:keys [v s e key test]} p
        newitem   (:new p)
        st        (:st p)
        [st limit] (count-limit st (:keys p) e)
        dst       (if in-place? v (gensym "dst"))
        st        (if in-place? st (conj st dst (subseq-form backend v 0 (list (api 'length) v))))
        r         (counter backend "r")
        build
        (fn [fe]
          (index-loop
           backend s e fe (if limit [[r 0]] [])
           (fn [i nxt]
             (let [el     (gensym "el")
                   hit    (list 'do (store dst i newitem) (apply nxt (if limit [(list 'inc r)] [])))
                   miss   (apply nxt (if limit [r] []))
                   tested (apply-key key el (fn [kv] (test kv (fn [t] (list 'if t hit miss)))))
                   step   (list 'let [el (list (api 'elt) v i)] tested)]
               ;; the count used up: the rest stays as it is
               (if limit (list 'if (list '< r limit) step dst) step)))
           dst))]
    (finish st (both-directions (:from-end p) build))))

;; ===========================================================================
;; The registry (I23)
;; ===========================================================================

(defn ^:macro-support expand
  "The expansion of a sequence-function call: a loop, or for a curried form a
   literal fn of the sequence (D48)."
  [backend form]
  (let [fname (name (first form))
        spec  (get (specs) fname)
        shape (call-shape spec (rest form))]
    (case shape
      :curried (let [s (gensym "sequence")]
                 (list 'fn [s] (splice-sequence spec form s)))
      :full    (case fname
                 ("count" "count-if" "count-if-not")          (expand-count backend form)
                 ("find" "find-if" "find-if-not")             (expand-find backend form)
                 ("position" "position-if" "position-if-not") (expand-position backend form)
                 "reduce"                                     (expand-reduce backend form)
                 "fill"                                       (expand-fill backend form)
                 "replace"                                    (expand-replace backend form)
                 "subseq"                                     (expand-subseq backend form)
                 "copy-seq"                                   (expand-copy-seq backend form)
                 "reverse"                                    (expand-reverse backend form)
                 "nreverse"                                   (expand-nreverse backend form)
                 ("sort" "stable-sort")                       (expand-sort backend form)
                 ("remove" "remove-if" "remove-if-not" "delete" "delete-if" "delete-if-not")
                 (expand-remove backend form)
                 ("substitute" "substitute-if" "substitute-if-not"
                  "nsubstitute" "nsubstitute-if" "nsubstitute-if-not")
                 (expand-substitute backend form)
                 (expand-quantifier backend form))
      (contract/fail! (str "malformed " fname ": " (pr-str form) ". Write " (usage fname)
                           (when-not (:rest spec)
                             (str ", or leave out the sequence for a function of it (a curried form)")))
                      {:form form}))))

(defn ^:macro-support expanders
  "The registry entries of the sequence functions. A form is one of them
   only when called through ucl's alias with every argument (a curried form is
   a function value, not a loop)."
  []
  (into {}
        (map (fn [[fname spec]]
               [fname {:applies? (fn [form] (and (ucl-call? form)
                                                 (= :full (call-shape spec (rest form)))))
                       :expand   expand}]))
        (specs)))
