(ns ucl.seq
  "Common Lisp's sequence functions over vectors (README §4.2, D44–D52).

   Each is one shared expansion over ucl's own forms, registered with the
   contract (I23): return-position assignment (D35) runs one as a statement
   and the walker expands one before walking it. The macros themselves are
   generated by contract/defapi from `contract/vocabulary-names`.

   A function argument -- a predicate, `reduce`'s function, `:key`, `:test` --
   is applied in one of four ways (D46–D48):
     a literal fn       its body is written into the loop, its parameters
                        bound to the elements
     a symbol           called in function position
     a curried form     a sequence function short of its sequence: the
                        element is spliced in as that sequence
     anything else      evaluated once, before the loop, and called
   Applying one takes a continuation, the code that uses its value. A literal
   fn's body ends in `let` or `do` often; written into an `if` test or a
   `recur` argument as it is, that would be an expression-position `let`, an
   IIFE on Squint (H22). So the continuation is pushed into the body's tail,
   unless a name the body binds occurs in the continuation's code.

   An expander never reads the lexical environment (I23): what needs a local's
   type it emits as a ucl form, `ucl.api/elt` and `ucl.api/length`, which
   expand later where the environment is right.

   Squint loads this file into its macro interpreter only if the word
   d-e-f-m-a-c-r-o appears in it (H6): defmacro -- the marker is load-bearing."
  (:require [ucl.contract :as contract]))

;; ===========================================================================
;; Small helpers
;; ===========================================================================

(defn ^:macro-support api [sym] (symbol "ucl.api" (name sym)))

(defn ^:macro-support ucl-call?
  "Is `form` a call through a namespace other than Clojure's own? Clients
   always call ucl through its alias (D25); a bare `count` or `reduce` is
   Clojure's, and the walker must leave it alone."
  [form]
  (let [h (first form)]
    (and (symbol? h)
         (some? (namespace h))
         (not (contains? #{"clojure.core" "cljs.core" "cljd.core"} (namespace h))))))

(defn ^:macro-support keyword-tail?
  "Alternating literal keywords and values."
  [xs]
  (and (even? (count xs)) (every? keyword? (take-nth 2 xs))))

(defn ^:macro-support counter
  "A fresh loop counter, hinted as a fixnum where the host types locals by
   hint (I20)."
  [backend prefix]
  (let [v (gensym prefix)
        h ((contract/op backend :types :local-hint) :fixnum)]
    (if h (vary-meta v assoc :tag h) v)))

(defn ^:macro-support binder
  "Bindings evaluated once, left to right, in the order they are added.
   `(bind st form prefix)` returns [st' ref]: a trivial form is used as is."
  [] [])

(defn ^:macro-support bind [st form prefix]
  (if (contract/trivial? form)
    [st form]
    (let [g (gensym prefix)] [(conj st g form) g])))

;; ===========================================================================
;; The functions: required arguments, keywords, curried forms (D48, D50)
;; ===========================================================================
;; Every function here takes its sequence second. `:rest` -- the `every`
;; family takes one or more sequences and has no curried form (D50).

(defn ^:macro-support specs []
  {"count"            {:nreq 2 :keys #{:from-end :start :end :key :test :test-not}}
   "count-if"         {:nreq 2 :keys #{:from-end :start :end :key}}
   "count-if-not"     {:nreq 2 :keys #{:from-end :start :end :key}}
   "find"             {:nreq 2 :keys #{:from-end :start :end :key :test :test-not}}
   "find-if"          {:nreq 2 :keys #{:from-end :start :end :key}}
   "find-if-not"      {:nreq 2 :keys #{:from-end :start :end :key}}
   "position"         {:nreq 2 :keys #{:from-end :start :end :key :test :test-not}}
   "position-if"      {:nreq 2 :keys #{:from-end :start :end :key}}
   "position-if-not"  {:nreq 2 :keys #{:from-end :start :end :key}}
   "reduce"           {:nreq 2 :keys #{:key :from-end :start :end :initial-value}}
   "every"            {:nreq 2 :rest true}
   "some"             {:nreq 2 :rest true}
   "notany"           {:nreq 2 :rest true}
   "notevery"         {:nreq 2 :rest true}})

(defn ^:macro-support call-shape
  "`:full`, `:curried` (every argument but the sequence), or nil."
  [spec args]
  (let [n (:nreq spec)]
    (cond (:rest spec)                         (when (>= (count args) n) :full)
          (and (>= (count args) n)
               (keyword-tail? (drop n args)))  :full
          (and (= n 2) (>= (count args) 1)
               (keyword-tail? (drop 1 args)))  :curried
          :else nil)))

(defn ^:macro-support usage [fname]
  (case fname
    ("count" "find" "position") (str "(" fname " item sequence &key from-end start end key test test-not)")
    "reduce"                    "(reduce function sequence &key key from-end start end initial-value)"
    ("every" "some" "notany" "notevery") (str "(" fname " predicate sequence &rest sequences)")
    (str "(" fname " predicate sequence &key from-end start end key)")))

(defn ^:macro-support parse-keys
  "The keyword arguments of a call, in written order, after checking them:
   a key the function does not take is allowed only when the leftmost
   `:allow-other-keys` is true (CLHS 3.4.1.4.1). A macro decides that at
   expansion, so with other keys present the value must be a literal."
  [fname spec kvs form]
  (let [pairs   (mapv vec (partition 2 kvs))
        aok     (first (filter #(= :allow-other-keys (first %)) pairs))
        unknown (remove #(or (contains? (:keys spec) (first %)) (= :allow-other-keys (first %))) pairs)]
    (when (seq unknown)
      (let [k (ffirst unknown)
            v (second aok)]
        (cond
          (nil? aok)
          (contract/fail! (str fname " does not take " k ". It takes "
                               (pr-str (vec (sort (:keys spec)))) ", or others with :allow-other-keys true -- "
                               (usage fname))
                          {:form form})
          (not (contract/literal? v))
          (contract/fail! (str fname " is given " k " with :allow-other-keys " (pr-str v)
                               ", which is only known at run time. Write :allow-other-keys true, or leave out " k)
                          {:form form})
          (or (nil? v) (false? v))
          (contract/fail! (str fname " does not take " k " (:allow-other-keys is " (pr-str v) ")")
                          {:form form}))))
    {:order pairs}))

(defn ^:macro-support literal-nil? [f] (nil? f))

;; ===========================================================================
;; Applying a function argument (D46–D48)
;; ===========================================================================

(defn ^:macro-support fn-literal? [f]
  (and (seq? f) (contains? #{"fn" "fn*"} (contract/head-name f))))

(defn ^:macro-support fn-arity
  "[params body] of the literal fn `f`'s arity for `n` arguments, or nil: no
   such arity, a rest parameter, or a named fn whose body calls itself."
  [f n]
  (let [more     (rest f)
        fname    (when (symbol? (first more)) (first more))
        more     (if fname (rest more) more)
        arities  (if (vector? (first more)) [more] more)
        hit      (first (filter (fn [a] (and (seq? a) (vector? (first a))
                                             (= n (count (first a)))
                                             (not (some #{'&} (first a)))))
                                (if (vector? (first more)) [more] arities)))]
    (when (and hit (not (and fname (contract/mentions? (rest hit) #{fname}))))
      [(first hit) (rest hit)])))

(defn ^:macro-support curried-form?
  "A sequence function given every argument but its sequence (D48)."
  [f]
  (and (seq? f) (symbol? (first f)) (ucl-call? f)
       (let [spec (get (specs) (name (first f)))]
         (and spec (= :curried (call-shape spec (rest f)))))))

(defn ^:macro-support designator
  "The function a quoted symbol or `#'f` names: `'f` is Common Lisp's
   designator for the global function f (CLHS 1.4.1.5), and Clojure reads
   `#'f` as `(var f)`."
  [f]
  (when (and (seq? f) (contains? #{'quote 'var} (first f)) (symbol? (second f)) (nil? (nnext f)))
    (second f)))

(defn ^:macro-support fn-spec
  "How to apply the function argument `f`, given the binder; returns [st spec]."
  [st f]
  (cond (fn-literal? f)    [st {:kind :inline :form f}]
        (symbol? f)        [st {:kind :call :f f}]
        (designator f)     [st {:kind :call :f (designator f)}]
        (curried-form? f)  [st {:kind :curried :form f}]
        :else              (let [[st g] (bind st f "f")] [st {:kind :call :f g}])))

(defn ^:macro-support push-into
  "`(k body)`, with `k` pushed into the tail of `body` when that is a `let` or
   `do` and pushing captures nothing; see the namespace doc."
  [body k]
  (let [h (contract/head-name body)]
    (cond
      (and (contains? #{"let" "let*"} h) (vector? (second body)) (seq (nnext body)))
      (let [bound (set (contract/binding-symbols (vec (take-nth 2 (second body)))))]
        (if (contract/mentions? (k (gensym "probe")) bound)
          (k body)
          (concat (butlast body) [(push-into (last body) k)])))

      (and (= "do" h) (seq (rest body)))
      (concat (butlast body) [(push-into (last body) k)])

      :else (k body))))

(defn ^:macro-support apply-fn
  "Apply the function argument `spec` to `args` (forms that are free to repeat:
   symbols), passing the value's form to the continuation `k`."
  [spec args k]
  (case (:kind spec)
    :identity (k (first args))
    :call     (k (cons (:f spec) args))
    :curried  (let [[h a0 & kws] (:form spec)] (k (list* h a0 (first args) kws)))
    :inline   (let [[params body] (or (fn-arity (:form spec) (count args))
                                      (contract/fail!
                                       (str "the fn " (pr-str (:form spec)) " takes no "
                                            (count args) " arguments, but is called with "
                                            (count args) " here")
                                       {:form (:form spec)}))
                    body (if (next body) (cons 'do body) (first body))
                    bound (set (contract/binding-symbols params))]
                (if (contract/mentions? (k (gensym "probe")) bound)
                  (k (list 'let (vec (interleave params args)) body))
                  (list 'let (vec (interleave params args)) (push-into body k))))))

(defn ^:macro-support apply-key
  "Apply `:key` (identity when absent) to the element `e`, then `k`."
  [key-spec e k]
  (apply-fn (or key-spec {:kind :identity}) [e] k))

(defn ^:macro-support item-test
  "The continuation-passing test of `item` against a key value: `:test`,
   `:test-not` or `eql` (D52)."
  [backend fname test-spec test-not-spec item form]
  (when (and test-spec test-not-spec)
    (contract/fail! (str fname " takes :test or :test-not, not both (CLHS 17.2.1)")
                    {:form form}))
  (cond test-spec     (fn [kv k] (apply-fn test-spec [item kv] k))
        test-not-spec (fn [kv k] (apply-fn test-not-spec [item kv] (fn [t] (k (list 'not t)))))
        :else         (fn [kv k] (k ((contract/op backend :seqfn :eql) item kv)))))

;; ===========================================================================
;; Index loops
;; ===========================================================================

(defn ^:macro-support bind-keys
  "Evaluate every keyword value once, in written order; the leftmost
   occurrence of a key is the one used (CLHS 3.4.1.4). Keys in `fn-keys` take
   functions; a literal nil `:key` is identity (CLHS 17.2.1). Returns
   [st {key ref-or-spec}]."
  [st order fn-keys]
  (reduce (fn [[st m] [k f]]
            (let [use (fn [st x] [st (if (contains? m k) m (assoc m k x))])]
              (cond (and (= :key k) (literal-nil? f)) (use st nil)
                    (contains? fn-keys k)             (let [[st x] (fn-spec st f)] (use st x))
                    :else                             (let [[st x] (bind st f (name k))] (use st x)))))
          [st {}] order))

(defn ^:macro-support index-loop
  "(loop [i first, state...] (if in-range (body i next) exit)), stepping up
   from `s` below `e`, or down from below `e` to `s` when `from-end`.
   `body` gets the counter and `next`, a fn of the new state values that
   returns the `recur`."
  [backend s e from-end state body exit]
  (let [i      (counter backend "i")
        first* (if from-end (list 'dec e) s)
        test   (if from-end (list '>= i s) (list '< i e))
        step   (if from-end (list 'dec i) (list 'inc i))
        nxt    (fn [& vals] (list* 'recur step vals))]
    (list 'loop (vec (concat [i first*] (mapcat identity state)))
          (list 'if test (body i nxt) exit))))

(defn ^:macro-support bounds
  "[st s e]: the `:start` and `:end` of sequence `v`. An `:end` that is not a
   literal may be nil at run time, meaning the length (CLHS 17.1.1)."
  [st v keys]
  (let [s (get keys :start 0)
        e (get keys :end)]
    [st s (cond (nil? e)    (list (api 'length) v)
                (number? e) e
                :else       (list 'if (list 'nil? e) (list (api 'length) v) e))]))

(defn ^:macro-support finish [st body] (contract/wrap-let st body))

;; ===========================================================================
;; count, find, position (and their -if, -if-not)
;; ===========================================================================

(defn ^:macro-support parse-search
  "Shared front of the item and predicate searches: binds arguments in
   CLHS order -- the item or predicate, the sequence, then each keyword value
   as written -- and returns what an expansion needs."
  [backend fname form]
  (let [spec        (get (specs) fname)
        [_ a0 sq & kvs] form
        if?         (not (contains? #{"count" "find" "position"} fname))
        st          (binder)
        [st item pred] (if if?
                         (let [[st p] (fn-spec st a0)] [st nil p])
                         (let [[st x] (bind st a0 "item")] [st x nil]))
        [st v]      (bind st sq "v")
        {:keys [order]} (parse-keys fname spec kvs form)
        [st kforms] (bind-keys st order #{:key :test :test-not})
        [st s e]    (bounds st v kforms)
        [st s]      (bind st s "s")
        [st e]      (bind st e "e")
        negate?     (and if? (.endsWith ^String fname "-not"))
        test        (if if?
                      (fn [kv k] (apply-fn pred [kv] (if negate? (fn [t] (k (list 'not t))) k)))
                      (item-test backend fname (:test kforms) (:test-not kforms) item form))]
    {:st st :v v :s s :e e :from-end (get kforms :from-end) :key (:key kforms) :test test}))

(defn ^:macro-support search-loop
  "A search in one direction: `found` builds the return value from the
   element and the index."
  [backend {:keys [v s e key test]} from-end found exit-value]
  (index-loop backend s e from-end []
              (fn [i nxt]
                (let [el (gensym "el")]
                  (list 'let [el (list (api 'elt) v i)]
                        (apply-key key el
                                   (fn [kv] (test kv (fn [t] (list 'if t (found el i) (nxt)))))))))
              exit-value))

(defn ^:macro-support both-directions
  "A `:from-end` known at compile time picks one loop; otherwise both are
   emitted and the flag chooses at run time."
  [from-end build]
  (cond (or (nil? from-end) (false? from-end)) (build false)
        (true? from-end)                       (build true)
        :else (list 'if from-end (build true) (build false))))

(defn ^:macro-support expand-count [backend form]
  ;; :from-end changes only the order the test sees the elements in
  (let [p (parse-search backend (name (first form)) form)
        c (counter backend "c")]
    (finish (:st p)
            (both-directions
             (:from-end p)
             (fn [fe]
               (index-loop backend (:s p) (:e p) fe [[c 0]]
                           (fn [i nxt]
                             (let [el (gensym "el")]
                               (list 'let [el (list (api 'elt) (:v p) i)]
                                     (apply-key (:key p) el
                                                (fn [kv] ((:test p) kv
                                                          (fn [t] (nxt (list 'if t (list 'inc c) c)))))))))
                           c))))))

(defn ^:macro-support expand-find [backend form]
  (let [p (parse-search backend (name (first form)) form)]
    (finish (:st p) (both-directions (:from-end p)
                                     (fn [fe] (search-loop backend p fe (fn [el _] el) nil))))))

(defn ^:macro-support expand-position [backend form]
  (let [p (parse-search backend (name (first form)) form)]
    (finish (:st p) (both-directions (:from-end p)
                                     (fn [fe] (search-loop backend p fe (fn [_ i] i) nil))))))

;; ===========================================================================
;; every, some, notany, notevery
;; ===========================================================================

(defn ^:macro-support expand-quantifier [backend form]
  (let [fname   (name (first form))
        [_ f & seqs] form
        st      (binder)
        [st pred] (fn-spec st f)
        [st vs] (reduce (fn [[st acc] sq] (let [[st v] (bind st sq "v")] [st (conj acc v)]))
                        [st []] seqs)
        n       (if (next vs)
                  (cons (api 'min) (map #(list (api 'length) %) vs))
                  (list (api 'length) (first vs)))
        [st n]  (bind st n "n")
        r       (gensym "r")
        on-true (fn [t nxt] (case fname
                              "every"    (list 'if t (nxt) nil)
                              "some"     (list 'let [r t] (list 'if r r (nxt)))
                              "notany"   (list 'if t nil (nxt))
                              "notevery" (list 'if t (nxt) true)))
        exit    (case fname "every" true "some" nil "notany" true "notevery" nil)]
    (finish st
            (index-loop backend 0 n false []
                        (fn [i nxt]
                          (let [els (mapv (fn [_] (gensym "el")) vs)]
                            (list 'let (vec (mapcat (fn [el v] [el (list (api 'elt) v i)]) els vs))
                                  (apply-fn pred els (fn [t] (on-true t nxt))))))
                        exit))))

;; ===========================================================================
;; reduce
;; ===========================================================================

(defn ^:macro-support operator-name
  "The name of an arithmetic or comparison operator: Clojure's, unqualified or
   from clojure.core, or ucl's min and max."
  [f]
  (when (symbol? f)
    (let [ns (namespace f)]
      (when (or (nil? ns) (contains? #{"clojure.core" "cljs.core" "cljd.core"} ns)
                (contains? #{"min" "max"} (name f)))
        (name f)))))

(defn ^:macro-support operator-zero
  "The value of a call with no arguments, for the operators that have one."
  [f]
  (case (operator-name f) "+" 0 "*" 1 nil))

(defn ^:macro-support operator-needs-args? [f]
  (contains? #{"-" "/" "min" "max" "<" ">" "<=" ">=" "==" "=" "not=" "quot" "rem" "mod"
               "bit-and" "bit-or" "bit-xor"}
             (operator-name f)))

(defn ^:macro-support zero-call
  "`(function)`, for an empty range without :initial-value (CLHS reduce)."
  [backend spec form]
  (cond (and (= :call (:kind spec)) (operator-zero (:f spec)))
        (operator-zero (:f spec))

        ;; an operator that needs arguments: hosts inline operators, and a
        ;; call with none can fail to compile (Squint emits `()`)
        (and (= :call (:kind spec)) (operator-needs-args? (:f spec)))
        (if (pos? (contract/safety backend))
          ((contract/op backend :seqfn :fail)
           (str "reduce of an empty sequence without :initial-value calls " (:f spec)
                " with no arguments"))
          nil)

        (= :call (:kind spec))
        (list (:f spec))
        (and (= :inline (:kind spec)) (fn-arity (:form spec) 0))
        (apply-fn spec [] identity)
        (pos? (contract/safety backend))
        ((contract/op backend :seqfn :fail)
         (str "reduce of an empty sequence without :initial-value calls its function with no arguments, which "
              (pr-str (or (:form spec) (:f spec))) " does not take"))
        :else nil))

(defn ^:macro-support expand-reduce [backend form]
  (let [[_ f sq & kvs] form
        spec      (get (specs) "reduce")
        st        (binder)
        [st fs]   (fn-spec st f)
        [st v]    (bind st sq "v")
        {:keys [order]} (parse-keys "reduce" spec kvs form)
        [st kf]   (bind-keys st order #{:key})
        [st s e]  (bounds st v kf)
        [st s]    (bind st s "s")
        [st e]    (bind st e "e")
        init?     (contains? kf :initial-value)
        acc       (gensym "acc")
        step      (fn [fe]
                    (fn [i nxt]
                      (let [el (gensym "el")]
                        (list 'let [el (list (api 'elt) v i)]
                              (apply-key (:key kf) el
                                         (fn [kv] (apply-fn fs (if fe [kv acc] [acc kv])
                                                            (fn [r] (nxt r)))))))))
        build     (fn [fe]
                    (if init?
                      (index-loop backend s e fe [[acc (:initial-value kf)]] (step fe) acc)
                      (let [el    (gensym "el")
                            first (if fe (list 'dec e) s)
                            ;; the loop runs over what is left after the first element
                            [s' e'] (if fe [s (list 'dec e)] [(list 'inc s) e])]
                        (list 'if (list '< s e)
                              (list 'let [el (list (api 'elt) v first)]
                                    (apply-key (:key kf) el
                                               (fn [kv] (index-loop backend s' e' fe [[acc kv]] (step fe) acc))))
                              (zero-call backend fs form)))))]
    (finish st (both-directions (:from-end kf) build))))

;; ===========================================================================
;; The registry (I23)
;; ===========================================================================

(defn ^:macro-support expand
  "The expansion of a sequence-function call: a loop, or for a curried form a
   literal fn of the sequence (D48)."
  [backend form]
  (let [fname (name (first form))
        spec  (get (specs) fname)
        shape (call-shape spec (rest form))]
    (case shape
      :curried (let [s (gensym "sequence")
                     [h a0 & kws] form]
                 (list 'fn [s] (list* h a0 s kws)))
      :full    (case fname
                 ("count" "count-if" "count-if-not")          (expand-count backend form)
                 ("find" "find-if" "find-if-not")             (expand-find backend form)
                 ("position" "position-if" "position-if-not") (expand-position backend form)
                 "reduce"                                     (expand-reduce backend form)
                 (expand-quantifier backend form))
      (contract/fail! (str "malformed " fname ": " (pr-str form) ". Write " (usage fname)
                           (when-not (:rest spec)
                             (str ", or leave out the sequence for a function of it (a curried form)")))
                      {:form form}))))

(defn ^:macro-support expanders
  "The registry entries of the sequence functions. A form is one of them
   only when called through ucl's alias with every argument (a curried form is
   a function value, not a loop)."
  []
  (into {}
        (map (fn [[fname spec]]
               [fname {:applies? (fn [form] (and (ucl-call? form)
                                                 (= :full (call-shape spec (rest form)))))
                       :expand   expand}]))
        (specs)))
