;; Writes .clj-kondo/hooks/ucl_api.clj: what `defapi` defines, for clj-kondo
;; and clojure-lsp, which read source and cannot expand it (I54). Rerun after
;; adding or documenting an operator:
;;
;;   clojure -M:jvm ucl/kondo.clj
;;
;; Every name, docstring and arglist comes from the JVM's ucl.api as loaded. A
;; vocabulary operator takes `[& args]` (a curried form is short of its
;; sequence); the rest take the arities they are written with.
(ns ucl.kondo
  (:require [clojure.java.io]
            [clojure.pprint :as pp]
            [ucl.api]
            [ucl.contract :as contract]))

(def out ".clj-kondo/hooks/ucl_api.clj")

(def extrema
  ;; macros on the JS hosts and ClojureDart; inline functions on the JVM,
  ;; which defines them in its own file (`:inline-extrema?`)
  (for [n '[min max]]
    `(~'defmacro ~n ~(str "(" n " real...) -- inline in call position, a function as a value.")
       {:arglists '~'([& reals])} [~'& ~'args])))

(defn stub [[s v]]
  (let [{:keys [doc arglists]} (meta v)
        vocab (set (map name (contract/vocabulary-names)))
        params (if (contains? vocab (name s)) '([& args]) arglists)]
    `(~'defmacro ~s ~@(when doc [doc]) {:arglists '~arglists}
       ~@(map list params))))

(let [stubs (->> (ns-publics 'ucl.api)
                 (filter (fn [[_ v]] (:macro (meta v))))
                 (sort-by key)
                 (map stub))
      hook `(~'defmacro ~'defapi [~'_ & [~'opts]]
              (~'cons '~'do (~'concat '~stubs
                                      (~'when-not (:inline-extrema? ~'opts) '~extrema))))]
  (clojure.java.io/make-parents out)
  (spit out
        (str ";; Generated by ucl/kondo.clj from the JVM's ucl.api -- do not edit.\n"
             "(ns hooks.ucl-api)\n\n"
             (with-out-str (binding [pp/*print-right-margin* 100]
                               (pp/with-pprint-dispatch pp/code-dispatch (pp/pprint hook))))))
  (println "wrote" out (count stubs) "macros"))
