;; Generated by ucl/kondo.clj from the JVM's ucl.api -- do not edit.
(ns hooks.ucl-api)

(defmacro defapi [_ & [opts]]
  (cons
    'do
    (concat
      '((defmacro block
          "(block name body...) -- `return-from` name leaves it with a value."
          {:arglists '([block-name & body])}
          ([block-name & body]))
         (defmacro concatenate
           "(concatenate result-type &rest sequences)\n\nA fresh vector of result-type holding every sequence's elements in order.\n\nCommon Lisp's concatenate on vectors (CLHS 17), expanded inline."
           {:arglists '([result-type & sequences])}
           ([& args]))
         (defmacro copy-seq
           "(copy-seq sequence)\n\nA fresh copy of the sequence.\n\nCommon Lisp's copy-seq on vectors (CLHS 17), expanded inline. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence])}
           ([& args]))
         (defmacro count
           "(count item sequence &key from-end start end key test test-not)\n\nThe number of elements that satisfy the test.\n\nCommon Lisp's count on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([item sequence & {:keys [from-end start end key test test-not]}])}
           ([& args]))
         (defmacro count-if
           "(count-if predicate sequence &key from-end start end key)\n\nThe number of elements that satisfy the test.\n\nCommon Lisp's count-if on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end key]}])}
           ([& args]))
         (defmacro count-if-not
           "(count-if-not predicate sequence &key from-end start end key)\n\nThe number of elements that satisfy the test.\n\nCommon Lisp's count-if-not on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end key]}])}
           ([& args]))
         (defmacro decf
           "(decf place [delta]) -- returns the new value."
           {:arglists '([place] [place delta])}
           ([place])
           ([place delta]))
         (defmacro defmethod
           "(defmethod name ((self Struct) params...) [doc] (declare ...) body...)"
           {:arglists '([mname lambda-list & body])}
           ([mname lambda-list & body]))
         (defmacro defstruct
           "(defstruct (Name (:constructor Name (args &optional .. &aux ..))) slot...)"
           {:arglists '([name-and-options & slots])}
           ([name-and-options & slots]))
         (defmacro defun
           "(defun name (params) [doc] (declare ...) body...)"
           {:arglists '([fname lambda-list & body])}
           ([fname lambda-list & body]))
         (defmacro delete
           "(delete item sequence &key from-end test test-not start end count key)\n\nremove, allowed to modify the sequence.\n\nCommon Lisp's delete on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([item sequence & {:keys [from-end test test-not start end count key]}])}
           ([& args]))
         (defmacro delete-duplicates
           "(delete-duplicates sequence &key from-end test test-not start end key)\n\nremove-duplicates, allowed to modify the sequence.\n\nCommon Lisp's delete-duplicates on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence & {:keys [from-end test test-not start end key]}])}
           ([& args]))
         (defmacro delete-if
           "(delete-if predicate sequence &key from-end start end count key)\n\nremove, allowed to modify the sequence.\n\nCommon Lisp's delete-if on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end count key]}])}
           ([& args]))
         (defmacro delete-if-not
           "(delete-if-not predicate sequence &key from-end start end count key)\n\nremove, allowed to modify the sequence.\n\nCommon Lisp's delete-if-not on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end count key]}])}
           ([& args]))
         (defmacro dotimes
           "(dotimes (var count [result]) (declare ...) body...)"
           {:arglists '([spec & body])}
           ([spec & body]))
         (defmacro elt
           "(elt sequence index) -- read an element; a place for setf."
           {:arglists '([sequence index])}
           ([sequence index]))
         (defmacro every
           "(every predicate sequence &rest sequences)\n\nTrue when the predicate is true of every element (of every sequence, in parallel).\n\nCommon Lisp's every on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop."
           {:arglists '([predicate sequence & sequences])}
           ([& args]))
         (defmacro fill
           "(fill sequence item &key start end)\n\nStores item at every index of [start, end); returns sequence.\n\nCommon Lisp's fill on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence item & {:keys [start end]}])}
           ([& args]))
         (defmacro find
           "(find item sequence &key from-end start end key test test-not)\n\nThe leftmost element that satisfies the test (the rightmost with :from-end), or nil.\n\nCommon Lisp's find on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([item sequence & {:keys [from-end start end key test test-not]}])}
           ([& args]))
         (defmacro find-if
           "(find-if predicate sequence &key from-end start end key)\n\nThe leftmost element that satisfies the test (the rightmost with :from-end), or nil.\n\nCommon Lisp's find-if on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end key]}])}
           ([& args]))
         (defmacro find-if-not
           "(find-if-not predicate sequence &key from-end start end key)\n\nThe leftmost element that satisfies the test (the rightmost with :from-end), or nil.\n\nCommon Lisp's find-if-not on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end key]}])}
           ([& args]))
         (defmacro gethash
           "(gethash key hash-table [default]) -- a place for setf."
           {:arglists '([key hash-table & default])}
           ([key hash-table & default]))
         (defmacro incf
           "(incf place [delta]) -- returns the new value."
           {:arglists '([place] [place delta])}
           ([place])
           ([place delta]))
         (defmacro length
           "(length sequence) -- respects the fill pointer."
           {:arglists '([sequence])}
           ([sequence]))
         (defmacro let
           "(let ((var init)...) (declare ...) body...) -- bind in parallel; the\n         variables can be assigned with setf, incf and decf."
           {:arglists '([bindings & body])}
           ([bindings & body]))
         (defmacro let*
           "(let* ((var init)...) (declare ...) body...) -- bind in order; the\n         variables can be assigned with setf, incf and decf."
           {:arglists '([bindings & body])}
           ([bindings & body]))
         (defmacro loop
           "(loop clause...)\n\nCommon Lisp's LOOP for vectors and numbers: for ... across, for ... from/below/to/by, for k being the hash-keys of h [using (hash-value v)], for ... and ..., sum/count/maximize/minimize [into v] [of-type T], when/unless/else, while/until/repeat, always/never/thereis, with, initially, finally, named; (loop-finish) ends it. No list clauses.\n\nClojure's loop/recur, with a binding vector, is the unqualified `loop`."
           {:arglists '([& clauses])}
           ([& args]))
         (defmacro loop-finish
           "(loop-finish)\n\nEnds the enclosing ucl/loop normally: its finally clauses run and it returns its accumulated value."
           {:arglists '([])}
           ([& args]))
         (defmacro make-array
           "(make-array n &key element-type initial-element initial-contents adjustable fill-pointer)"
           {:arglists
            '([n
               &
               {:keys [element-type initial-element initial-contents adjustable fill-pointer]}])}
           ([n & {:keys [element-type initial-element initial-contents adjustable fill-pointer]}]))
         (defmacro make-hash-table
           "(make-hash-table &key test size initial-contents)"
           {:arglists '([& {:keys [test size initial-contents]}])}
           ([& {:keys [test size initial-contents]}]))
         (defmacro make-sequence
           "(make-sequence result-type size &key initial-element)\n\nA fresh vector of result-type with size elements.\n\nCommon Lisp's make-sequence on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop."
           {:arglists '([result-type size & {:keys [initial-element]}])}
           ([& args]))
         (defmacro map
           "(map result-type function sequence &rest sequences)\n\nA vector of result-type of the function's values over the elements, in parallel; nil for effect only.\n\nCommon Lisp's map on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop."
           {:arglists '([result-type function sequence & sequences])}
           ([& args]))
         (defmacro map-into
           "(map-into result-sequence function &rest sequences)\n\nStores the function's values over the sequences into result-sequence and returns it.\n\nCommon Lisp's map-into on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop."
           {:arglists '([result-sequence function & sequences])}
           ([& args]))
         (defmacro merge
           "(merge result-type sequence-1 sequence-2 predicate &key key)\n\nA stable merge of two sequences sorted by predicate, as a vector of result-type.\n\nCommon Lisp's merge on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([result-type sequence-1 sequence-2 predicate & {:keys [key]}])}
           ([& args]))
         (defmacro mismatch
           "(mismatch sequence-1 sequence-2 &key from-end test test-not key start1 start2 end1 end2)\n\nThe index in sequence-1 where the two sequences first differ, or nil.\n\nCommon Lisp's mismatch on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists
            '([sequence-1
               sequence-2
               &
               {:keys [from-end test test-not key start1 start2 end1 end2]}])}
           ([& args]))
         (defmacro notany
           "(notany predicate sequence &rest sequences)\n\nTrue when the predicate is false of every element.\n\nCommon Lisp's notany on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop."
           {:arglists '([predicate sequence & sequences])}
           ([& args]))
         (defmacro notevery
           "(notevery predicate sequence &rest sequences)\n\nTrue when the predicate is false of some element.\n\nCommon Lisp's notevery on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop."
           {:arglists '([predicate sequence & sequences])}
           ([& args]))
         (defmacro nreverse
           "(nreverse sequence)\n\nReverses the sequence in place and returns it.\n\nCommon Lisp's nreverse on vectors (CLHS 17), expanded inline. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence])}
           ([& args]))
         (defmacro nsubstitute
           "(nsubstitute newitem olditem sequence &key from-end test test-not start end count key)\n\nsubstitute, in place: returns the sequence.\n\nCommon Lisp's nsubstitute on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists
            '([newitem olditem sequence & {:keys [from-end test test-not start end count key]}])}
           ([& args]))
         (defmacro nsubstitute-if
           "(nsubstitute-if newitem predicate sequence &key from-end start end count key)\n\nsubstitute, in place: returns the sequence.\n\nCommon Lisp's nsubstitute-if on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([newitem predicate sequence & {:keys [from-end start end count key]}])}
           ([& args]))
         (defmacro nsubstitute-if-not
           "(nsubstitute-if-not newitem predicate sequence &key from-end start end count key)\n\nsubstitute, in place: returns the sequence.\n\nCommon Lisp's nsubstitute-if-not on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([newitem predicate sequence & {:keys [from-end start end count key]}])}
           ([& args]))
         (defmacro position
           "(position item sequence &key from-end start end key test test-not)\n\nThe index of the leftmost element that satisfies the test (the rightmost with :from-end), or nil.\n\nCommon Lisp's position on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([item sequence & {:keys [from-end start end key test test-not]}])}
           ([& args]))
         (defmacro position-if
           "(position-if predicate sequence &key from-end start end key)\n\nThe index of the leftmost element that satisfies the test (the rightmost with :from-end), or nil.\n\nCommon Lisp's position-if on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end key]}])}
           ([& args]))
         (defmacro position-if-not
           "(position-if-not predicate sequence &key from-end start end key)\n\nThe index of the leftmost element that satisfies the test (the rightmost with :from-end), or nil.\n\nCommon Lisp's position-if-not on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end key]}])}
           ([& args]))
         (defmacro princ-to-string
           "(princ-to-string object) -- an integer's decimal digits, or a string itself."
           {:arglists '([object])}
           ([object]))
         (defmacro reduce
           "(reduce function sequence &key key from-end start end initial-value)\n\nThe elements combined by a function of two arguments, left-associatively (right with :from-end).\n\nCommon Lisp's reduce on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([function sequence & {:keys [key from-end start end initial-value]}])}
           ([& args]))
         (defmacro remove
           "(remove item sequence &key from-end test test-not start end count key)\n\nA fresh vector without the elements that satisfy the test (at most :count of them).\n\nCommon Lisp's remove on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([item sequence & {:keys [from-end test test-not start end count key]}])}
           ([& args]))
         (defmacro remove-duplicates
           "(remove-duplicates sequence &key from-end test test-not start end key)\n\nA fresh vector keeping one of each set of equal elements: the last, or the first with :from-end.\n\nCommon Lisp's remove-duplicates on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence & {:keys [from-end test test-not start end key]}])}
           ([& args]))
         (defmacro remove-if
           "(remove-if predicate sequence &key from-end start end count key)\n\nA fresh vector without the elements that satisfy the test (at most :count of them).\n\nCommon Lisp's remove-if on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end count key]}])}
           ([& args]))
         (defmacro remove-if-not
           "(remove-if-not predicate sequence &key from-end start end count key)\n\nA fresh vector without the elements that satisfy the test (at most :count of them).\n\nCommon Lisp's remove-if-not on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([predicate sequence & {:keys [from-end start end count key]}])}
           ([& args]))
         (defmacro replace
           "(replace sequence-1 sequence-2 &key start1 end1 start2 end2)\n\nCopies the elements of sequence-2 into sequence-1, in place; returns sequence-1.\n\nCommon Lisp's replace on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence-1 sequence-2 & {:keys [start1 end1 start2 end2]}])}
           ([& args]))
         (defmacro return
           "(return [value]) -- leave the enclosing block nil (ucl/dotimes, ucl/loop)."
           {:arglists '([& value])}
           ([& value]))
         (defmacro return-from
           "(return-from name [value]) -- leave the enclosing block `name`."
           {:arglists '([block-name & value])}
           ([block-name & value]))
         (defmacro reverse
           "(reverse sequence)\n\nA fresh vector of the elements in reverse order.\n\nCommon Lisp's reverse on vectors (CLHS 17), expanded inline. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence])}
           ([& args]))
         (defmacro search
           "(search sequence-1 sequence-2 &key from-end test test-not key start1 start2 end1 end2)\n\nThe index in sequence-2 where sequence-1 first occurs, or nil.\n\nCommon Lisp's search on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists
            '([sequence-1
               sequence-2
               &
               {:keys [from-end test test-not key start1 start2 end1 end2]}])}
           ([& args]))
         (defmacro setf
           "(setf place value ...) -- assign; returns the last value."
           {:arglists '([place value & more-places-and-values])}
           ([place value & more-places-and-values]))
         (defmacro slot-value
           "(slot-value object 'slot) -- a place for setf."
           {:arglists '([object slot])}
           ([object slot]))
         (defmacro some
           "(some predicate sequence &rest sequences)\n\nThe predicate's first true value over the elements, or nil.\n\nCommon Lisp's some on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop."
           {:arglists '([predicate sequence & sequences])}
           ([& args]))
         (defmacro sort
           "(sort sequence predicate &key key)\n\nSorts the sequence in place by predicate and returns it.\n\nCommon Lisp's sort on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence predicate & {:keys [key]}])}
           ([& args]))
         (defmacro stable-sort
           "(stable-sort sequence predicate &key key)\n\nSorts the sequence in place by predicate, equal elements keeping their order, and returns it.\n\nCommon Lisp's stable-sort on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence predicate & {:keys [key]}])}
           ([& args]))
         (defmacro subseq
           "(subseq sequence start &optional end)\n\nA fresh vector of the elements in [start, end). A place for setf: (setf (subseq v s e) new).\n\nCommon Lisp's subseq on vectors (CLHS 17), expanded inline. Called without its sequence, it is a function of the sequence."
           {:arglists '([sequence start] [sequence start end])}
           ([& args]))
         (defmacro substitute
           "(substitute newitem olditem sequence &key from-end test test-not start end count key)\n\nA fresh vector with newitem in place of each element that satisfies the test (at most :count).\n\nCommon Lisp's substitute on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists
            '([newitem olditem sequence & {:keys [from-end test test-not start end count key]}])}
           ([& args]))
         (defmacro substitute-if
           "(substitute-if newitem predicate sequence &key from-end start end count key)\n\nA fresh vector with newitem in place of each element that satisfies the test (at most :count).\n\nCommon Lisp's substitute-if on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([newitem predicate sequence & {:keys [from-end start end count key]}])}
           ([& args]))
         (defmacro substitute-if-not
           "(substitute-if-not newitem predicate sequence &key from-end start end count key)\n\nA fresh vector with newitem in place of each element that satisfies the test (at most :count).\n\nCommon Lisp's substitute-if-not on vectors (CLHS 17), expanded inline. A literal fn argument is written into the loop. Called without its sequence, it is a function of the sequence."
           {:arglists '([newitem predicate sequence & {:keys [from-end start end count key]}])}
           ([& args]))
         (defmacro vector-push-extend
           "(vector-push-extend new-element vector) -- returns the new element's index."
           {:arglists '([new-element vector])}
           ([new-element vector]))
         (defmacro with-slots
           "(with-slots (slot...) object body...)"
           {:arglists '([slots object & body])}
           ([slots object & body])))
      (when-not (:inline-extrema? opts)
        '((defmacro min
            "(min real...) -- inline in call position, a function as a value."
            {:arglists '([& reals])}
            [& args])
           (defmacro max
             "(max real...) -- inline in call position, a function as a value."
             {:arglists '([& reals])}
             [& args]))))))
